# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWin(object):
    def setupUi(self, ConfigWin):
        ConfigWin.setObjectName("ConfigWin")
        ConfigWin.resize(800, 684)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigWin.sizePolicy().hasHeightForWidth())
        ConfigWin.setSizePolicy(sizePolicy)
        ConfigWin.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.frame = QtWidgets.QFrame(ConfigWin)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 329))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(177, 206, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 15, 205, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.textEntry = QtWidgets.QLineEdit(self.frame)
        self.textEntry.setGeometry(QtCore.QRect(50, 50, 405, 34))
        self.textEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.textEntry.setObjectName("textEntry")
        self.nameEntry = QtWidgets.QLineEdit(self.frame)
        self.nameEntry.setGeometry(QtCore.QRect(480, 50, 270, 34))
        self.nameEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.nameEntry.setObjectName("nameEntry")
        self.authorEntry = QtWidgets.QLineEdit(self.frame)
        self.authorEntry.setGeometry(QtCore.QRect(550, 120, 200, 30))
        self.authorEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.authorEntry.setObjectName("authorEntry")
        self.receiverEntry = QtWidgets.QLineEdit(self.frame)
        self.receiverEntry.setGeometry(QtCore.QRect(550, 187, 200, 30))
        self.receiverEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.receiverEntry.setObjectName("receiverEntry")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(480, 19, 173, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 92, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.topicbox = QtWidgets.QListWidget(self.frame)
        self.topicbox.setGeometry(QtCore.QRect(50, 120, 201, 128))
        self.topicbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.topicbox.setObjectName("topicbox")
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(280, 92, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(266, 125, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(266, 192, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(550, 95, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(550, 162, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.fdayMenu = QtWidgets.QComboBox(self.frame)
        self.fdayMenu.setGeometry(QtCore.QRect(300, 120, 50, 30))
        self.fdayMenu.setStyleSheet("")
        self.fdayMenu.setObjectName("fdayMenu")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.tyearMenu = QtWidgets.QComboBox(self.frame)
        self.tyearMenu.setGeometry(QtCore.QRect(435, 187, 70, 30))
        self.tyearMenu.setObjectName("tyearMenu")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(300, 230, 205, 18))
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.fyearMenu = QtWidgets.QComboBox(self.frame)
        self.fyearMenu.setGeometry(QtCore.QRect(435, 120, 70, 30))
        self.fyearMenu.setObjectName("fyearMenu")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fmonthMenu = QtWidgets.QComboBox(self.frame)
        self.fmonthMenu.setGeometry(QtCore.QRect(365, 120, 60, 30))
        self.fmonthMenu.setObjectName("fmonthMenu")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.tdayMenu = QtWidgets.QComboBox(self.frame)
        self.tdayMenu.setGeometry(QtCore.QRect(300, 187, 50, 30))
        self.tdayMenu.setStyleSheet("")
        self.tdayMenu.setObjectName("tdayMenu")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 267, 800, 62))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.newConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.newConfigBtn.setGeometry(QtCore.QRect(20, 15, 180, 32))
        self.newConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
"color: rgb(255, 255, 255)")
        self.newConfigBtn.setObjectName("newConfigBtn")
        self.saveConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.saveConfigBtn.setGeometry(QtCore.QRect(213, 15, 180, 32))
        self.saveConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
"color: rgb(255, 255, 255)")
        self.saveConfigBtn.setObjectName("saveConfigBtn")
        self.delConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.delConfigBtn.setGeometry(QtCore.QRect(407, 15, 180, 32))
        self.delConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
"color: rgb(255, 255, 255)")
        self.delConfigBtn.setObjectName("delConfigBtn")
        self.useConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.useConfigBtn.setGeometry(QtCore.QRect(600, 15, 180, 32))
        self.useConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
"color: rgb(255, 255, 255)")
        self.useConfigBtn.setObjectName("useConfigBtn")
        self.tmonthMenu = QtWidgets.QComboBox(self.frame)
        self.tmonthMenu.setGeometry(QtCore.QRect(365, 187, 60, 30))
        self.tmonthMenu.setObjectName("tmonthMenu")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.frame_2 = QtWidgets.QFrame(ConfigWin)
        self.frame_2.setGeometry(QtCore.QRect(20, 329, 760, 335))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(177, 206, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.configbox = QtWidgets.QTreeWidget(self.frame_2)
        self.configbox.setGeometry(QtCore.QRect(30, 47, 700, 258))
        self.configbox.setObjectName("configbox")
        item_0 = QtWidgets.QTreeWidgetItem(self.configbox)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(30, 13, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(ConfigWin)
        QtCore.QMetaObject.connectSlotsByName(ConfigWin)

    def retranslateUi(self, ConfigWin):
        _translate = QtCore.QCoreApplication.translate
        ConfigWin.setWindowTitle(_translate("ConfigWin", "Менеджер конфигураций"))
        self.label_3.setText(_translate("ConfigWin", "Текст содержит слова:"))
        self.label_4.setText(_translate("ConfigWin", "Название конфигурации:"))
        self.label_5.setText(_translate("ConfigWin", "Рубрики:"))
        __sortingEnabled = self.topicbox.isSortingEnabled()
        self.topicbox.setSortingEnabled(False)
        item = self.topicbox.item(0)
        item.setText(_translate("ConfigWin", "Все"))
        item = self.topicbox.item(1)
        item.setText(_translate("ConfigWin", "11-19 век"))
        item = self.topicbox.item(2)
        item.setText(_translate("ConfigWin", "1917-1939"))
        item = self.topicbox.item(3)
        item.setText(_translate("ConfigWin", "1941"))
        item = self.topicbox.item(4)
        item.setText(_translate("ConfigWin", "WWI"))
        item = self.topicbox.item(5)
        item.setText(_translate("ConfigWin", "WWII"))
        item = self.topicbox.item(6)
        item.setText(_translate("ConfigWin", "Администрации"))
        item = self.topicbox.item(7)
        item.setText(_translate("ConfigWin", "Армия"))
        item = self.topicbox.item(8)
        item.setText(_translate("ConfigWin", "Артиллерия"))
        item = self.topicbox.item(9)
        item.setText(_translate("ConfigWin", "Байки"))
        item = self.topicbox.item(10)
        item.setText(_translate("ConfigWin", "ВВС"))
        item = self.topicbox.item(11)
        item.setText(_translate("ConfigWin", "Военные игры"))
        item = self.topicbox.item(12)
        item.setText(_translate("ConfigWin", "Древняя история"))
        item = self.topicbox.item(13)
        item.setText(_translate("ConfigWin", "Евреи и Израиль"))
        item = self.topicbox.item(14)
        item.setText(_translate("ConfigWin", "Загадки"))
        item = self.topicbox.item(15)
        item.setText(_translate("ConfigWin", "Искусство и творчество"))
        item = self.topicbox.item(16)
        item.setText(_translate("ConfigWin", "Космос"))
        item = self.topicbox.item(17)
        item.setText(_translate("ConfigWin", "Локальные конфликты"))
        item = self.topicbox.item(18)
        item.setText(_translate("ConfigWin", "Мусор"))
        item = self.topicbox.item(19)
        item.setText(_translate("ConfigWin", "Память"))
        item = self.topicbox.item(20)
        item.setText(_translate("ConfigWin", "Политек"))
        item = self.topicbox.item(21)
        item.setText(_translate("ConfigWin", "Прочее"))
        item = self.topicbox.item(22)
        item.setText(_translate("ConfigWin", "Ремонтная бригада"))
        item = self.topicbox.item(23)
        item.setText(_translate("ConfigWin", "Современность"))
        item = self.topicbox.item(24)
        item.setText(_translate("ConfigWin", "Спецслужбы"))
        item = self.topicbox.item(25)
        item.setText(_translate("ConfigWin", "Стрелковое оружие"))
        item = self.topicbox.item(26)
        item.setText(_translate("ConfigWin", "Суворов (В.Резун)"))
        item = self.topicbox.item(27)
        item.setText(_translate("ConfigWin", "Танки"))
        item = self.topicbox.item(28)
        item.setText(_translate("ConfigWin", "Униформа"))
        item = self.topicbox.item(29)
        item.setText(_translate("ConfigWin", "Флот"))
        item = self.topicbox.item(30)
        item.setText(_translate("ConfigWin", "Фортификация"))
        self.topicbox.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("ConfigWin", "Дата:"))
        self.label_7.setText(_translate("ConfigWin", "От:"))
        self.label_8.setText(_translate("ConfigWin", "До:"))
        self.label_9.setText(_translate("ConfigWin", "Автор:"))
        self.label_10.setText(_translate("ConfigWin", "Адрессат:"))
        self.fdayMenu.setItemText(0, _translate("ConfigWin", "1"))
        self.fdayMenu.setItemText(1, _translate("ConfigWin", "2"))
        self.fdayMenu.setItemText(2, _translate("ConfigWin", "3"))
        self.fdayMenu.setItemText(3, _translate("ConfigWin", "4"))
        self.fdayMenu.setItemText(4, _translate("ConfigWin", "5"))
        self.fdayMenu.setItemText(5, _translate("ConfigWin", "6"))
        self.fdayMenu.setItemText(6, _translate("ConfigWin", "7"))
        self.fdayMenu.setItemText(7, _translate("ConfigWin", "8"))
        self.fdayMenu.setItemText(8, _translate("ConfigWin", "9"))
        self.fdayMenu.setItemText(9, _translate("ConfigWin", "10"))
        self.fdayMenu.setItemText(10, _translate("ConfigWin", "11"))
        self.fdayMenu.setItemText(11, _translate("ConfigWin", "12"))
        self.fdayMenu.setItemText(12, _translate("ConfigWin", "13"))
        self.fdayMenu.setItemText(13, _translate("ConfigWin", "14"))
        self.fdayMenu.setItemText(14, _translate("ConfigWin", "15"))
        self.fdayMenu.setItemText(15, _translate("ConfigWin", "16"))
        self.fdayMenu.setItemText(16, _translate("ConfigWin", "17"))
        self.fdayMenu.setItemText(17, _translate("ConfigWin", "18"))
        self.fdayMenu.setItemText(18, _translate("ConfigWin", "19"))
        self.fdayMenu.setItemText(19, _translate("ConfigWin", "20"))
        self.fdayMenu.setItemText(20, _translate("ConfigWin", "21"))
        self.fdayMenu.setItemText(21, _translate("ConfigWin", "22"))
        self.fdayMenu.setItemText(22, _translate("ConfigWin", "23"))
        self.fdayMenu.setItemText(23, _translate("ConfigWin", "24"))
        self.fdayMenu.setItemText(24, _translate("ConfigWin", "25"))
        self.fdayMenu.setItemText(25, _translate("ConfigWin", "26"))
        self.fdayMenu.setItemText(26, _translate("ConfigWin", "27"))
        self.fdayMenu.setItemText(27, _translate("ConfigWin", "28"))
        self.fdayMenu.setItemText(28, _translate("ConfigWin", "29"))
        self.fdayMenu.setItemText(29, _translate("ConfigWin", "30"))
        self.fdayMenu.setItemText(30, _translate("ConfigWin", "31"))
        self.tyearMenu.setItemText(0, _translate("ConfigWin", "2000"))
        self.tyearMenu.setItemText(1, _translate("ConfigWin", "2001"))
        self.tyearMenu.setItemText(2, _translate("ConfigWin", "2002"))
        self.tyearMenu.setItemText(3, _translate("ConfigWin", "2003"))
        self.tyearMenu.setItemText(4, _translate("ConfigWin", "2004"))
        self.tyearMenu.setItemText(5, _translate("ConfigWin", "2005"))
        self.tyearMenu.setItemText(6, _translate("ConfigWin", "2006"))
        self.tyearMenu.setItemText(7, _translate("ConfigWin", "2007"))
        self.tyearMenu.setItemText(8, _translate("ConfigWin", "2008"))
        self.tyearMenu.setItemText(9, _translate("ConfigWin", "2009"))
        self.tyearMenu.setItemText(10, _translate("ConfigWin", "2010"))
        self.tyearMenu.setItemText(11, _translate("ConfigWin", "2011"))
        self.tyearMenu.setItemText(12, _translate("ConfigWin", "2012"))
        self.tyearMenu.setItemText(13, _translate("ConfigWin", "2013"))
        self.tyearMenu.setItemText(14, _translate("ConfigWin", "2014"))
        self.tyearMenu.setItemText(15, _translate("ConfigWin", "2015"))
        self.tyearMenu.setItemText(16, _translate("ConfigWin", "2016"))
        self.tyearMenu.setItemText(17, _translate("ConfigWin", "2017"))
        self.tyearMenu.setItemText(18, _translate("ConfigWin", "2018"))
        self.tyearMenu.setItemText(19, _translate("ConfigWin", "2019"))
        self.tyearMenu.setItemText(20, _translate("ConfigWin", "2020"))
        self.checkBox.setText(_translate("ConfigWin", "Расширенный вывод"))
        self.fyearMenu.setItemText(0, _translate("ConfigWin", "2000"))
        self.fyearMenu.setItemText(1, _translate("ConfigWin", "2001"))
        self.fyearMenu.setItemText(2, _translate("ConfigWin", "2002"))
        self.fyearMenu.setItemText(3, _translate("ConfigWin", "2003"))
        self.fyearMenu.setItemText(4, _translate("ConfigWin", "2004"))
        self.fyearMenu.setItemText(5, _translate("ConfigWin", "2005"))
        self.fyearMenu.setItemText(6, _translate("ConfigWin", "2006"))
        self.fyearMenu.setItemText(7, _translate("ConfigWin", "2007"))
        self.fyearMenu.setItemText(8, _translate("ConfigWin", "2008"))
        self.fyearMenu.setItemText(9, _translate("ConfigWin", "2009"))
        self.fyearMenu.setItemText(10, _translate("ConfigWin", "2010"))
        self.fyearMenu.setItemText(11, _translate("ConfigWin", "2011"))
        self.fyearMenu.setItemText(12, _translate("ConfigWin", "2012"))
        self.fyearMenu.setItemText(13, _translate("ConfigWin", "2013"))
        self.fyearMenu.setItemText(14, _translate("ConfigWin", "2014"))
        self.fyearMenu.setItemText(15, _translate("ConfigWin", "2015"))
        self.fyearMenu.setItemText(16, _translate("ConfigWin", "2016"))
        self.fyearMenu.setItemText(17, _translate("ConfigWin", "2017"))
        self.fyearMenu.setItemText(18, _translate("ConfigWin", "2018"))
        self.fyearMenu.setItemText(19, _translate("ConfigWin", "2019"))
        self.fyearMenu.setItemText(20, _translate("ConfigWin", "2020"))
        self.fmonthMenu.setItemText(0, _translate("ConfigWin", "Янв"))
        self.fmonthMenu.setItemText(1, _translate("ConfigWin", "Фев"))
        self.fmonthMenu.setItemText(2, _translate("ConfigWin", "Мар"))
        self.fmonthMenu.setItemText(3, _translate("ConfigWin", "Апр"))
        self.fmonthMenu.setItemText(4, _translate("ConfigWin", "Май"))
        self.fmonthMenu.setItemText(5, _translate("ConfigWin", "Июн"))
        self.fmonthMenu.setItemText(6, _translate("ConfigWin", "Июл"))
        self.fmonthMenu.setItemText(7, _translate("ConfigWin", "Авг"))
        self.fmonthMenu.setItemText(8, _translate("ConfigWin", "Сен"))
        self.fmonthMenu.setItemText(9, _translate("ConfigWin", "Окт"))
        self.fmonthMenu.setItemText(10, _translate("ConfigWin", "Ноя"))
        self.fmonthMenu.setItemText(11, _translate("ConfigWin", "Дек"))
        self.tdayMenu.setItemText(0, _translate("ConfigWin", "1"))
        self.tdayMenu.setItemText(1, _translate("ConfigWin", "2"))
        self.tdayMenu.setItemText(2, _translate("ConfigWin", "3"))
        self.tdayMenu.setItemText(3, _translate("ConfigWin", "4"))
        self.tdayMenu.setItemText(4, _translate("ConfigWin", "5"))
        self.tdayMenu.setItemText(5, _translate("ConfigWin", "6"))
        self.tdayMenu.setItemText(6, _translate("ConfigWin", "7"))
        self.tdayMenu.setItemText(7, _translate("ConfigWin", "8"))
        self.tdayMenu.setItemText(8, _translate("ConfigWin", "9"))
        self.tdayMenu.setItemText(9, _translate("ConfigWin", "10"))
        self.tdayMenu.setItemText(10, _translate("ConfigWin", "11"))
        self.tdayMenu.setItemText(11, _translate("ConfigWin", "12"))
        self.tdayMenu.setItemText(12, _translate("ConfigWin", "13"))
        self.tdayMenu.setItemText(13, _translate("ConfigWin", "14"))
        self.tdayMenu.setItemText(14, _translate("ConfigWin", "15"))
        self.tdayMenu.setItemText(15, _translate("ConfigWin", "16"))
        self.tdayMenu.setItemText(16, _translate("ConfigWin", "17"))
        self.tdayMenu.setItemText(17, _translate("ConfigWin", "18"))
        self.tdayMenu.setItemText(18, _translate("ConfigWin", "19"))
        self.tdayMenu.setItemText(19, _translate("ConfigWin", "20"))
        self.tdayMenu.setItemText(20, _translate("ConfigWin", "21"))
        self.tdayMenu.setItemText(21, _translate("ConfigWin", "22"))
        self.tdayMenu.setItemText(22, _translate("ConfigWin", "23"))
        self.tdayMenu.setItemText(23, _translate("ConfigWin", "24"))
        self.tdayMenu.setItemText(24, _translate("ConfigWin", "25"))
        self.tdayMenu.setItemText(25, _translate("ConfigWin", "26"))
        self.tdayMenu.setItemText(26, _translate("ConfigWin", "27"))
        self.tdayMenu.setItemText(27, _translate("ConfigWin", "28"))
        self.tdayMenu.setItemText(28, _translate("ConfigWin", "29"))
        self.tdayMenu.setItemText(29, _translate("ConfigWin", "30"))
        self.tdayMenu.setItemText(30, _translate("ConfigWin", "31"))
        self.newConfigBtn.setText(_translate("ConfigWin", "Новая"))
        self.saveConfigBtn.setText(_translate("ConfigWin", "Сохранить"))
        self.delConfigBtn.setText(_translate("ConfigWin", "Удалить"))
        self.useConfigBtn.setText(_translate("ConfigWin", "Использовать"))
        self.tmonthMenu.setItemText(0, _translate("ConfigWin", "Янв"))
        self.tmonthMenu.setItemText(1, _translate("ConfigWin", "Фев"))
        self.tmonthMenu.setItemText(2, _translate("ConfigWin", "Мар"))
        self.tmonthMenu.setItemText(3, _translate("ConfigWin", "Апр"))
        self.tmonthMenu.setItemText(4, _translate("ConfigWin", "Май"))
        self.tmonthMenu.setItemText(5, _translate("ConfigWin", "Июн"))
        self.tmonthMenu.setItemText(6, _translate("ConfigWin", "Июл"))
        self.tmonthMenu.setItemText(7, _translate("ConfigWin", "Авг"))
        self.tmonthMenu.setItemText(8, _translate("ConfigWin", "Сен"))
        self.tmonthMenu.setItemText(9, _translate("ConfigWin", "Окт"))
        self.tmonthMenu.setItemText(10, _translate("ConfigWin", "Ноя"))
        self.tmonthMenu.setItemText(11, _translate("ConfigWin", "Дек"))
        self.configbox.headerItem().setText(0, _translate("ConfigWin", "Имя"))
        self.configbox.headerItem().setText(1, _translate("ConfigWin", "Текст"))
        self.configbox.headerItem().setText(2, _translate("ConfigWin", "Рубрика"))
        self.configbox.headerItem().setText(3, _translate("ConfigWin", "Нач. дата"))
        self.configbox.headerItem().setText(4, _translate("ConfigWin", "Кон. дата"))
        self.configbox.headerItem().setText(5, _translate("ConfigWin", "Автор"))
        self.configbox.headerItem().setText(6, _translate("ConfigWin", "Адресат"))
        self.configbox.headerItem().setText(7, _translate("ConfigWin", "Расш. поиск"))
        __sortingEnabled = self.configbox.isSortingEnabled()
        self.configbox.setSortingEnabled(False)
        self.configbox.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("ConfigWin", "Конфигурации:"))
