# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1427, 882)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1427, 882))
        MainWindow.setMaximumSize(QtCore.QSize(1427, 882))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 287, 882))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 20, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 20, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 20, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.menu.setPalette(palette)
        self.menu.setAutoFillBackground(False)
        self.menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "border: 2px solid rgb(177, 206, 240);")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.menubase = QtWidgets.QFrame(self.menu)
        self.menubase.setGeometry(QtCore.QRect(17, 541, 253, 297))
        self.menubase.setAutoFillBackground(False)
        self.menubase.setStyleSheet("border: 2px solid rgb(177, 206, 240);")
        self.menubase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menubase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menubase.setObjectName("menubase")
        self.guidefrm = QtWidgets.QFrame(self.menubase)
        self.guidefrm.setGeometry(QtCore.QRect(0, 0, 253, 58))
        self.guidefrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.guidefrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.guidefrm.setObjectName("guidefrm")
        self.guidelbl = QtWidgets.QLabel(self.guidefrm)
        self.guidelbl.setGeometry(QtCore.QRect(20, 15, 228, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.guidelbl.setFont(font)
        self.guidelbl.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.guidelbl.setObjectName("guidelbl")
        self.startBtn = QtWidgets.QPushButton(self.menubase)
        self.startBtn.setGeometry(QtCore.QRect(24, 137, 205, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                    "color: rgb(255, 255, 255)")
        self.startBtn.setObjectName("startBtn")
        self.label_5 = QtWidgets.QLabel(self.menubase)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.menubase)
        self.lineEdit.setGeometry(QtCore.QRect(174, 76, 51, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.lineEdit.setObjectName("lineEdit")
        self.guidefrm_2 = QtWidgets.QFrame(self.menubase)
        self.guidefrm_2.setGeometry(QtCore.QRect(0, 181, 253, 116))
        self.guidefrm_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.guidefrm_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.guidefrm_2.setObjectName("guidefrm_2")
        self.progresslbl = QtWidgets.QLabel(self.guidefrm_2)
        self.progresslbl.setGeometry(QtCore.QRect(24, 75, 205, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.progresslbl.setFont(font)
        self.progresslbl.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.progresslbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.progresslbl.setObjectName("progresslbl")
        self.progressBar = QtWidgets.QProgressBar(self.guidefrm_2)
        self.progressBar.setGeometry(QtCore.QRect(24, 30, 205, 32))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(17, 100, 253, 239))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../ico/badge.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.openSettings = QtWidgets.QPushButton(self.menu)
        self.openSettings.setGeometry(QtCore.QRect(17, 30, 253, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.openSettings.setFont(font)
        self.openSettings.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                        "color: rgb(255, 255, 255)")
        self.openSettings.setFlat(False)
        self.openSettings.setObjectName("openSettings")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(287, 0, 1145, 882))
        self.tabWidget.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.configfrm = QtWidgets.QFrame(self.main)
        self.configfrm.setGeometry(QtCore.QRect(38, 40, 353, 305))
        self.configfrm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "border: 2px solid rgb(177, 206, 240);")
        self.configfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configfrm.setObjectName("configfrm")
        self.configshow = QtWidgets.QTreeWidget(self.configfrm)
        self.configshow.setGeometry(QtCore.QRect(18, 45, 317, 239))
        self.configshow.setObjectName("configshow")
        self.configshow.header().setDefaultSectionSize(140)
        self.configshow.header().setMinimumSectionSize(90)
        self.label_3 = QtWidgets.QLabel(self.configfrm)
        self.label_3.setGeometry(QtCore.QRect(18, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.previewfrm = QtWidgets.QFrame(self.main)
        self.previewfrm.setGeometry(QtCore.QRect(424, 40, 681, 385))
        self.previewfrm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "border: 2px solid rgb(177, 206, 240);\n"
                                      "")
        self.previewfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.previewfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.previewfrm.setObjectName("previewfrm")
        self.label_2 = QtWidgets.QLabel(self.previewfrm)
        self.label_2.setGeometry(QtCore.QRect(14, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.previewfrm)
        self.frame.setGeometry(QtCore.QRect(14, 336, 649, 35))
        self.frame.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.expandedBtn = QtWidgets.QPushButton(self.frame)
        self.expandedBtn.setGeometry(QtCore.QRect(228, 7, 193, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.expandedBtn.setFont(font)
        self.expandedBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                       "color: rgb(255, 255, 255)")
        self.expandedBtn.setObjectName("expandedBtn")
        self.previewShowbox = QtWidgets.QTreeWidget(self.previewfrm)
        self.previewShowbox.setGeometry(QtCore.QRect(14, 45, 649, 293))
        self.previewShowbox.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.previewShowbox.setDragEnabled(True)
        self.previewShowbox.setObjectName("previewShowbox")
        self.previewShowbox.header().setDefaultSectionSize(200)
        self.previewShowbox.header().setMinimumSectionSize(150)
        self.configFullListfrm = QtWidgets.QFrame(self.main)
        self.configFullListfrm.setGeometry(QtCore.QRect(40, 379, 353, 463))
        self.configFullListfrm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "border: 2px solid rgb(177, 206, 240);\n"
                                             "")
        self.configFullListfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configFullListfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configFullListfrm.setObjectName("configFullListfrm")
        self.configFullListbox = QtWidgets.QTreeWidget(self.configFullListfrm)
        self.configFullListbox.setGeometry(QtCore.QRect(18, 46, 317, 345))
        self.configFullListbox.setObjectName("configFullListbox")
        self.configFullListbox.header().setDefaultSectionSize(140)
        self.configFullListbox.header().setMinimumSectionSize(90)
        self.label_4 = QtWidgets.QLabel(self.configFullListfrm)
        self.label_4.setGeometry(QtCore.QRect(18, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.managerBtn = QtWidgets.QPushButton(self.configFullListfrm)
        self.managerBtn.setGeometry(QtCore.QRect(74, 415, 205, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.managerBtn.setFont(font)
        self.managerBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                      "color: rgb(255, 255, 255)")
        self.managerBtn.setObjectName("managerBtn")
        self.exportfrm = QtWidgets.QFrame(self.main)
        self.exportfrm.setGeometry(QtCore.QRect(424, 471, 681, 367))
        self.exportfrm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "border: 2px solid rgb(177, 206, 240);")
        self.exportfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportfrm.setObjectName("exportfrm")
        self.buttonfrm = QtWidgets.QFrame(self.exportfrm)
        self.buttonfrm.setGeometry(QtCore.QRect(14, 316, 649, 35))
        self.buttonfrm.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.buttonfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonfrm.setObjectName("buttonfrm")
        self.renameBtn = QtWidgets.QPushButton(self.buttonfrm)
        self.renameBtn.setGeometry(QtCore.QRect(226, 7, 105, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.renameBtn.setFont(font)
        self.renameBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                     "color: rgb(255, 255, 255)")
        self.renameBtn.setObjectName("renameBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.buttonfrm)
        self.deleteBtn.setGeometry(QtCore.QRect(348, 7, 75, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                     "color: rgb(255, 255, 255)")
        self.deleteBtn.setObjectName("deleteBtn")
        self.label = QtWidgets.QLabel(self.exportfrm)
        self.label.setGeometry(QtCore.QRect(14, 10, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.exportbox = QtWidgets.QTreeWidget(self.exportfrm)
        self.exportbox.setGeometry(QtCore.QRect(14, 45, 649, 271))
        self.exportbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.exportbox.setDragEnabled(True)
        self.exportbox.setSelectionMode(
            QtWidgets.QAbstractItemView.ContiguousSelection)
        self.exportbox.setIndentation(25)
        self.exportbox.setObjectName("exportbox")
        self.exportbox.header().setVisible(False)
        self.exportbox.header().setCascadingSectionResizes(False)
        self.exportbox.header().setDefaultSectionSize(200)
        self.exportbox.header().setHighlightSections(False)
        self.exportbox.header().setMinimumSectionSize(150)
        self.tabWidget.addTab(self.main, "")
        self.manager = QtWidgets.QWidget()
        self.manager.setObjectName("manager")
        self.frame_2 = QtWidgets.QFrame(self.manager)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 1120, 462))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid rgb(177, 206, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(270, 150, 200, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.textEntry = QtWidgets.QLineEdit(self.frame_2)
        self.textEntry.setGeometry(QtCore.QRect(469, 150, 621, 34))
        self.textEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.textEntry.setObjectName("textEntry")
        self.nameEntry = QtWidgets.QLineEdit(self.frame_2)
        self.nameEntry.setGeometry(QtCore.QRect(340, 60, 460, 34))
        self.nameEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.nameEntry.setObjectName("nameEntry")
        self.authorEntry = QtWidgets.QLineEdit(self.frame_2)
        self.authorEntry.setGeometry(QtCore.QRect(650, 235, 440, 30))
        self.authorEntry.setStyleSheet("background-color: rgb(229, 240, 249);")
        self.authorEntry.setObjectName("authorEntry")
        self.receiverEntry = QtWidgets.QLineEdit(self.frame_2)
        self.receiverEntry.setGeometry(QtCore.QRect(650, 288, 440, 30))
        self.receiverEntry.setStyleSheet(
            "background-color: rgb(229, 240, 249);")
        self.receiverEntry.setObjectName("receiverEntry")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(462, 20, 216, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(50, 115, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.topicbox = QtWidgets.QListWidget(self.frame_2)
        self.topicbox.setGeometry(QtCore.QRect(50, 148, 201, 222))
        self.topicbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.topicbox.setObjectName("topicbox")
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.topicbox.addItem(item)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(280, 200, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(266, 235, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(266, 288, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(575, 235, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(575, 288, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.fdayMenu = QtWidgets.QComboBox(self.frame_2)
        self.fdayMenu.setGeometry(QtCore.QRect(300, 235, 50, 30))
        self.fdayMenu.setStyleSheet("")
        self.fdayMenu.setObjectName("fdayMenu")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.fdayMenu.addItem("")
        self.tyearMenu = QtWidgets.QComboBox(self.frame_2)
        self.tyearMenu.setGeometry(QtCore.QRect(435, 288, 70, 30))
        self.tyearMenu.setObjectName("tyearMenu")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.tyearMenu.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(300, 350, 205, 18))
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.fyearMenu = QtWidgets.QComboBox(self.frame_2)
        self.fyearMenu.setGeometry(QtCore.QRect(435, 235, 70, 30))
        self.fyearMenu.setObjectName("fyearMenu")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fyearMenu.addItem("")
        self.fmonthMenu = QtWidgets.QComboBox(self.frame_2)
        self.fmonthMenu.setGeometry(QtCore.QRect(365, 235, 60, 30))
        self.fmonthMenu.setObjectName("fmonthMenu")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.fmonthMenu.addItem("")
        self.tdayMenu = QtWidgets.QComboBox(self.frame_2)
        self.tdayMenu.setGeometry(QtCore.QRect(300, 288, 50, 30))
        self.tdayMenu.setStyleSheet("")
        self.tdayMenu.setObjectName("tdayMenu")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.tdayMenu.addItem("")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 398, 1120, 63))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.newConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.newConfigBtn.setGeometry(QtCore.QRect(50, 15, 200, 32))
        self.newConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                        "color: rgb(255, 255, 255)")
        self.newConfigBtn.setObjectName("newConfigBtn")
        self.renameConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.renameConfigBtn.setGeometry(QtCore.QRect(340, 15, 200, 32))
        self.renameConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                           "color: rgb(255, 255, 255)")
        self.renameConfigBtn.setObjectName("renameConfigBtn")
        self.delConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.delConfigBtn.setGeometry(QtCore.QRect(620, 15, 200, 32))
        self.delConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                        "color: rgb(255, 255, 255)")
        self.delConfigBtn.setObjectName("delConfigBtn")
        self.useConfigBtn = QtWidgets.QPushButton(self.frame_3)
        self.useConfigBtn.setGeometry(QtCore.QRect(890, 15, 200, 32))
        self.useConfigBtn.setStyleSheet("background-color: rgb(103, 169, 237);\n"
                                        "color: rgb(255, 255, 255)")
        self.useConfigBtn.setObjectName("useConfigBtn")
        self.tmonthMenu = QtWidgets.QComboBox(self.frame_2)
        self.tmonthMenu.setGeometry(QtCore.QRect(365, 288, 60, 30))
        self.tmonthMenu.setObjectName("tmonthMenu")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.tmonthMenu.addItem("")
        self.frame_4 = QtWidgets.QFrame(self.manager)
        self.frame_4.setGeometry(QtCore.QRect(20, 460, 1100, 372))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid rgb(177, 206, 240);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.configbox = QtWidgets.QTreeWidget(self.frame_4)
        self.configbox.setGeometry(QtCore.QRect(30, 47, 1040, 295))
        self.configbox.setObjectName("configbox")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(30, 13, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.manager, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(20, 20, 1100, 802))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid rgb(177, 206, 240);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_6)
        self.treeWidget.setGeometry(QtCore.QRect(20, 60, 1050, 396))
        self.treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(160)
        self.treeWidget.header().setMinimumSectionSize(40)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 1031, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget.setGeometry(QtCore.QRect(19, 457, 1061, 331))
        self.tableWidget.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(902)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.frame_5 = QtWidgets.QFrame(self.settings)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 1100, 802))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid rgb(177, 206, 240);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(520, 40, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.dateCheck = QtWidgets.QRadioButton(self.frame_5)
        self.dateCheck.setGeometry(QtCore.QRect(780, 300, 211, 31))
        self.dateCheck.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "font: 10pt \"Segoe UI\";\n"
                                     "")
        self.dateCheck.setObjectName("dateCheck")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.dateCheck)
        self.cfgCheck = QtWidgets.QRadioButton(self.frame_5)
        self.cfgCheck.setGeometry(QtCore.QRect(780, 240, 251, 31))
        self.cfgCheck.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "font: 10pt \"Segoe UI\";\n"
                                    "")
        self.cfgCheck.setChecked(True)
        self.cfgCheck.setObjectName("cfgCheck")
        self.buttonGroup.addButton(self.cfgCheck)
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(730, 170, 231, 51))
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "font: 10pt \"Segoe UI\";\n"
                                    "")
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(60, 170, 201, 41))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "font: 10pt \"Segoe UI\";\n"
                                    "")
        self.label_19.setObjectName("label_19")
        self.saveStgCheck = QtWidgets.QCheckBox(self.frame_5)
        self.saveStgCheck.setGeometry(QtCore.QRect(110, 230, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.saveStgCheck.setFont(font)
        self.saveStgCheck.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border-color: rgb(255, 255, 255);\n"
                                        "font: 10pt \"Segoe UI\";\n"
                                        "")
        self.saveStgCheck.setChecked(True)
        self.saveStgCheck.setAutoRepeat(False)
        self.saveStgCheck.setAutoExclusive(False)
        self.saveStgCheck.setObjectName("saveStgCheck")
        self.loadStgCheck = QtWidgets.QCheckBox(self.frame_5)
        self.loadStgCheck.setGeometry(QtCore.QRect(110, 300, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loadStgCheck.setFont(font)
        self.loadStgCheck.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border-color: rgb(255, 255, 255);\n"
                                        "font: 10pt \"Segoe UI\";\n"
                                        "")
        self.loadStgCheck.setChecked(True)
        self.loadStgCheck.setAutoRepeat(False)
        self.loadStgCheck.setAutoExclusive(False)
        self.loadStgCheck.setObjectName("loadStgCheck")
        self.exitCheck = QtWidgets.QCheckBox(self.frame_5)
        self.exitCheck.setGeometry(QtCore.QRect(110, 420, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exitCheck.setFont(font)
        self.exitCheck.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "font: 10pt \"Segoe UI\";\n"
                                     "")
        self.exitCheck.setChecked(True)
        self.exitCheck.setAutoRepeat(False)
        self.exitCheck.setAutoExclusive(False)
        self.exitCheck.setObjectName("exitCheck")
        self.exactTime = QtWidgets.QRadioButton(self.frame_5)
        self.exactTime.setGeometry(QtCore.QRect(780, 540, 251, 31))
        self.exactTime.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "font: 10pt \"Segoe UI\";\n"
                                     "")
        self.exactTime.setObjectName("exactTime")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.exactTime)
        self.relativetime = QtWidgets.QRadioButton(self.frame_5)
        self.relativetime.setGeometry(QtCore.QRect(780, 480, 251, 31))
        self.relativetime.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border-color: rgb(255, 255, 255);\n"
                                        "font: 10pt \"Segoe UI\";\n"
                                        "")
        self.relativetime.setChecked(True)
        self.relativetime.setObjectName("relativetime")
        self.buttonGroup_2.addButton(self.relativetime)
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(730, 410, 251, 51))
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "font: 10pt \"Segoe UI\";\n"
                                    "")
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.guidelbl.setText(_translate(
            "MainWindow", "Выберите конфигурацию!"))
        self.startBtn.setText(_translate("MainWindow", "Начать парсинг"))
        self.label_5.setText(_translate("MainWindow", "Количество страниц:\n"
                                        "(1 страница ≈ 100 запросов)"))
        self.progresslbl.setText(_translate(
            "MainWindow", "Выберите конфигурацию!"))
        self.openSettings.setText(_translate(
            "MainWindow", "Открыть настройки приложения"))
        self.configshow.setSortingEnabled(True)
        self.configshow.headerItem().setText(0, _translate("MainWindow", "Ключ"))
        self.configshow.headerItem().setText(1, _translate("MainWindow", "Значение"))
        self.label_3.setText(_translate("MainWindow", "Конфигурация:"))
        self.label_2.setText(_translate("MainWindow", "Предпросмотр:"))
        self.expandedBtn.setText(_translate(
            "MainWindow", "Расширенный предпросмотр"))
        self.previewShowbox.setSortingEnabled(True)
        self.previewShowbox.headerItem().setText(
            0, _translate("MainWindow", "Пользователь"))
        self.previewShowbox.headerItem().setText(
            1, _translate("MainWindow", "Сообщение"))
        self.previewShowbox.headerItem().setText(2, _translate("MainWindow", "Время"))
        self.configFullListbox.setSortingEnabled(True)
        self.configFullListbox.headerItem().setText(0, _translate("MainWindow", "Имя"))
        self.configFullListbox.headerItem().setText(
            1, _translate("MainWindow", "Последний парсинг"))
        self.label_4.setText(_translate("MainWindow", "История:"))
        self.managerBtn.setText(_translate(
            "MainWindow", "Открыть менеджер конфигураций"))
        self.renameBtn.setText(_translate("MainWindow", "Переименовать"))
        self.deleteBtn.setText(_translate("MainWindow", "Удалить"))
        self.label.setText(_translate("MainWindow", "Экспортированные файлы:"))
        self.exportbox.setSortingEnabled(True)
        self.exportbox.headerItem().setText(0, _translate("MainWindow", "Имя"))
        self.exportbox.headerItem().setText(1, _translate("MainWindow", "Кол-во записей"))
        self.exportbox.headerItem().setText(2, _translate("MainWindow", "Размер файла"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.main), _translate("MainWindow", "Основное окно"))
        self.label_7.setText(_translate("MainWindow", "Текст содержит слова:"))
        self.label_8.setText(_translate(
            "MainWindow", "Название конфигурации:"))
        self.label_9.setText(_translate("MainWindow", "Рубрики:"))
        __sortingEnabled = self.topicbox.isSortingEnabled()
        self.topicbox.setSortingEnabled(False)
        item = self.topicbox.item(0)
        item.setText(_translate("MainWindow", "Все"))
        item = self.topicbox.item(1)
        item.setText(_translate("MainWindow", "11-19 век"))
        item = self.topicbox.item(2)
        item.setText(_translate("MainWindow", "1917-1939"))
        item = self.topicbox.item(3)
        item.setText(_translate("MainWindow", "1941"))
        item = self.topicbox.item(4)
        item.setText(_translate("MainWindow", "WWI"))
        item = self.topicbox.item(5)
        item.setText(_translate("MainWindow", "WWII"))
        item = self.topicbox.item(6)
        item.setText(_translate("MainWindow", "Администрации"))
        item = self.topicbox.item(7)
        item.setText(_translate("MainWindow", "Армия"))
        item = self.topicbox.item(8)
        item.setText(_translate("MainWindow", "Артиллерия"))
        item = self.topicbox.item(9)
        item.setText(_translate("MainWindow", "Байки"))
        item = self.topicbox.item(10)
        item.setText(_translate("MainWindow", "ВВС"))
        item = self.topicbox.item(11)
        item.setText(_translate("MainWindow", "Военные игры"))
        item = self.topicbox.item(12)
        item.setText(_translate("MainWindow", "Древняя история"))
        item = self.topicbox.item(13)
        item.setText(_translate("MainWindow", "Евреи и Израиль"))
        item = self.topicbox.item(14)
        item.setText(_translate("MainWindow", "Загадки"))
        item = self.topicbox.item(15)
        item.setText(_translate("MainWindow", "Искусство и творчество"))
        item = self.topicbox.item(16)
        item.setText(_translate("MainWindow", "Космос"))
        item = self.topicbox.item(17)
        item.setText(_translate("MainWindow", "Локальные конфликты"))
        item = self.topicbox.item(18)
        item.setText(_translate("MainWindow", "Мусор"))
        item = self.topicbox.item(19)
        item.setText(_translate("MainWindow", "Память"))
        item = self.topicbox.item(20)
        item.setText(_translate("MainWindow", "Политек"))
        item = self.topicbox.item(21)
        item.setText(_translate("MainWindow", "Прочее"))
        item = self.topicbox.item(22)
        item.setText(_translate("MainWindow", "Ремонтная бригада"))
        item = self.topicbox.item(23)
        item.setText(_translate("MainWindow", "Современность"))
        item = self.topicbox.item(24)
        item.setText(_translate("MainWindow", "Спецслужбы"))
        item = self.topicbox.item(25)
        item.setText(_translate("MainWindow", "Стрелковое оружие"))
        item = self.topicbox.item(26)
        item.setText(_translate("MainWindow", "Суворов (В.Резун)"))
        item = self.topicbox.item(27)
        item.setText(_translate("MainWindow", "Танки"))
        item = self.topicbox.item(28)
        item.setText(_translate("MainWindow", "Униформа"))
        item = self.topicbox.item(29)
        item.setText(_translate("MainWindow", "Флот"))
        item = self.topicbox.item(30)
        item.setText(_translate("MainWindow", "Фортификация"))
        self.topicbox.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("MainWindow", "Дата:"))
        self.label_11.setText(_translate("MainWindow", "От:"))
        self.label_12.setText(_translate("MainWindow", "До:"))
        self.label_13.setText(_translate("MainWindow", "Автор:"))
        self.label_14.setText(_translate("MainWindow", "Адрессат:"))
        self.fdayMenu.setItemText(0, _translate("MainWindow", "1"))
        self.fdayMenu.setItemText(1, _translate("MainWindow", "2"))
        self.fdayMenu.setItemText(2, _translate("MainWindow", "3"))
        self.fdayMenu.setItemText(3, _translate("MainWindow", "4"))
        self.fdayMenu.setItemText(4, _translate("MainWindow", "5"))
        self.fdayMenu.setItemText(5, _translate("MainWindow", "6"))
        self.fdayMenu.setItemText(6, _translate("MainWindow", "7"))
        self.fdayMenu.setItemText(7, _translate("MainWindow", "8"))
        self.fdayMenu.setItemText(8, _translate("MainWindow", "9"))
        self.fdayMenu.setItemText(9, _translate("MainWindow", "10"))
        self.fdayMenu.setItemText(10, _translate("MainWindow", "11"))
        self.fdayMenu.setItemText(11, _translate("MainWindow", "12"))
        self.fdayMenu.setItemText(12, _translate("MainWindow", "13"))
        self.fdayMenu.setItemText(13, _translate("MainWindow", "14"))
        self.fdayMenu.setItemText(14, _translate("MainWindow", "15"))
        self.fdayMenu.setItemText(15, _translate("MainWindow", "16"))
        self.fdayMenu.setItemText(16, _translate("MainWindow", "17"))
        self.fdayMenu.setItemText(17, _translate("MainWindow", "18"))
        self.fdayMenu.setItemText(18, _translate("MainWindow", "19"))
        self.fdayMenu.setItemText(19, _translate("MainWindow", "20"))
        self.fdayMenu.setItemText(20, _translate("MainWindow", "21"))
        self.fdayMenu.setItemText(21, _translate("MainWindow", "22"))
        self.fdayMenu.setItemText(22, _translate("MainWindow", "23"))
        self.fdayMenu.setItemText(23, _translate("MainWindow", "24"))
        self.fdayMenu.setItemText(24, _translate("MainWindow", "25"))
        self.fdayMenu.setItemText(25, _translate("MainWindow", "26"))
        self.fdayMenu.setItemText(26, _translate("MainWindow", "27"))
        self.fdayMenu.setItemText(27, _translate("MainWindow", "28"))
        self.fdayMenu.setItemText(28, _translate("MainWindow", "29"))
        self.fdayMenu.setItemText(29, _translate("MainWindow", "30"))
        self.fdayMenu.setItemText(30, _translate("MainWindow", "31"))
        self.tyearMenu.setItemText(0, _translate("MainWindow", "2000"))
        self.tyearMenu.setItemText(1, _translate("MainWindow", "2001"))
        self.tyearMenu.setItemText(2, _translate("MainWindow", "2002"))
        self.tyearMenu.setItemText(3, _translate("MainWindow", "2003"))
        self.tyearMenu.setItemText(4, _translate("MainWindow", "2004"))
        self.tyearMenu.setItemText(5, _translate("MainWindow", "2005"))
        self.tyearMenu.setItemText(6, _translate("MainWindow", "2006"))
        self.tyearMenu.setItemText(7, _translate("MainWindow", "2007"))
        self.tyearMenu.setItemText(8, _translate("MainWindow", "2008"))
        self.tyearMenu.setItemText(9, _translate("MainWindow", "2009"))
        self.tyearMenu.setItemText(10, _translate("MainWindow", "2010"))
        self.tyearMenu.setItemText(11, _translate("MainWindow", "2011"))
        self.tyearMenu.setItemText(12, _translate("MainWindow", "2012"))
        self.tyearMenu.setItemText(13, _translate("MainWindow", "2013"))
        self.tyearMenu.setItemText(14, _translate("MainWindow", "2014"))
        self.tyearMenu.setItemText(15, _translate("MainWindow", "2015"))
        self.tyearMenu.setItemText(16, _translate("MainWindow", "2016"))
        self.tyearMenu.setItemText(17, _translate("MainWindow", "2017"))
        self.tyearMenu.setItemText(18, _translate("MainWindow", "2018"))
        self.tyearMenu.setItemText(19, _translate("MainWindow", "2019"))
        self.tyearMenu.setItemText(20, _translate("MainWindow", "2020"))
        self.checkBox.setText(_translate("MainWindow", "Расширенный вывод"))
        self.fyearMenu.setItemText(0, _translate("MainWindow", "2000"))
        self.fyearMenu.setItemText(1, _translate("MainWindow", "2001"))
        self.fyearMenu.setItemText(2, _translate("MainWindow", "2002"))
        self.fyearMenu.setItemText(3, _translate("MainWindow", "2003"))
        self.fyearMenu.setItemText(4, _translate("MainWindow", "2004"))
        self.fyearMenu.setItemText(5, _translate("MainWindow", "2005"))
        self.fyearMenu.setItemText(6, _translate("MainWindow", "2006"))
        self.fyearMenu.setItemText(7, _translate("MainWindow", "2007"))
        self.fyearMenu.setItemText(8, _translate("MainWindow", "2008"))
        self.fyearMenu.setItemText(9, _translate("MainWindow", "2009"))
        self.fyearMenu.setItemText(10, _translate("MainWindow", "2010"))
        self.fyearMenu.setItemText(11, _translate("MainWindow", "2011"))
        self.fyearMenu.setItemText(12, _translate("MainWindow", "2012"))
        self.fyearMenu.setItemText(13, _translate("MainWindow", "2013"))
        self.fyearMenu.setItemText(14, _translate("MainWindow", "2014"))
        self.fyearMenu.setItemText(15, _translate("MainWindow", "2015"))
        self.fyearMenu.setItemText(16, _translate("MainWindow", "2016"))
        self.fyearMenu.setItemText(17, _translate("MainWindow", "2017"))
        self.fyearMenu.setItemText(18, _translate("MainWindow", "2018"))
        self.fyearMenu.setItemText(19, _translate("MainWindow", "2019"))
        self.fyearMenu.setItemText(20, _translate("MainWindow", "2020"))
        self.fmonthMenu.setItemText(0, _translate("MainWindow", "Янв"))
        self.fmonthMenu.setItemText(1, _translate("MainWindow", "Фев"))
        self.fmonthMenu.setItemText(2, _translate("MainWindow", "Мар"))
        self.fmonthMenu.setItemText(3, _translate("MainWindow", "Апр"))
        self.fmonthMenu.setItemText(4, _translate("MainWindow", "Май"))
        self.fmonthMenu.setItemText(5, _translate("MainWindow", "Июн"))
        self.fmonthMenu.setItemText(6, _translate("MainWindow", "Июл"))
        self.fmonthMenu.setItemText(7, _translate("MainWindow", "Авг"))
        self.fmonthMenu.setItemText(8, _translate("MainWindow", "Сен"))
        self.fmonthMenu.setItemText(9, _translate("MainWindow", "Окт"))
        self.fmonthMenu.setItemText(10, _translate("MainWindow", "Ноя"))
        self.fmonthMenu.setItemText(11, _translate("MainWindow", "Дек"))
        self.tdayMenu.setItemText(0, _translate("MainWindow", "1"))
        self.tdayMenu.setItemText(1, _translate("MainWindow", "2"))
        self.tdayMenu.setItemText(2, _translate("MainWindow", "3"))
        self.tdayMenu.setItemText(3, _translate("MainWindow", "4"))
        self.tdayMenu.setItemText(4, _translate("MainWindow", "5"))
        self.tdayMenu.setItemText(5, _translate("MainWindow", "6"))
        self.tdayMenu.setItemText(6, _translate("MainWindow", "7"))
        self.tdayMenu.setItemText(7, _translate("MainWindow", "8"))
        self.tdayMenu.setItemText(8, _translate("MainWindow", "9"))
        self.tdayMenu.setItemText(9, _translate("MainWindow", "10"))
        self.tdayMenu.setItemText(10, _translate("MainWindow", "11"))
        self.tdayMenu.setItemText(11, _translate("MainWindow", "12"))
        self.tdayMenu.setItemText(12, _translate("MainWindow", "13"))
        self.tdayMenu.setItemText(13, _translate("MainWindow", "14"))
        self.tdayMenu.setItemText(14, _translate("MainWindow", "15"))
        self.tdayMenu.setItemText(15, _translate("MainWindow", "16"))
        self.tdayMenu.setItemText(16, _translate("MainWindow", "17"))
        self.tdayMenu.setItemText(17, _translate("MainWindow", "18"))
        self.tdayMenu.setItemText(18, _translate("MainWindow", "19"))
        self.tdayMenu.setItemText(19, _translate("MainWindow", "20"))
        self.tdayMenu.setItemText(20, _translate("MainWindow", "21"))
        self.tdayMenu.setItemText(21, _translate("MainWindow", "22"))
        self.tdayMenu.setItemText(22, _translate("MainWindow", "23"))
        self.tdayMenu.setItemText(23, _translate("MainWindow", "24"))
        self.tdayMenu.setItemText(24, _translate("MainWindow", "25"))
        self.tdayMenu.setItemText(25, _translate("MainWindow", "26"))
        self.tdayMenu.setItemText(26, _translate("MainWindow", "27"))
        self.tdayMenu.setItemText(27, _translate("MainWindow", "28"))
        self.tdayMenu.setItemText(28, _translate("MainWindow", "29"))
        self.tdayMenu.setItemText(29, _translate("MainWindow", "30"))
        self.tdayMenu.setItemText(30, _translate("MainWindow", "31"))
        self.newConfigBtn.setText(_translate("MainWindow", "Новая"))
        self.renameConfigBtn.setText(_translate("MainWindow", "Переименовать"))
        self.delConfigBtn.setText(_translate("MainWindow", "Удалить"))
        self.useConfigBtn.setText(_translate("MainWindow", "Использовать"))
        self.tmonthMenu.setItemText(0, _translate("MainWindow", "Янв"))
        self.tmonthMenu.setItemText(1, _translate("MainWindow", "Фев"))
        self.tmonthMenu.setItemText(2, _translate("MainWindow", "Мар"))
        self.tmonthMenu.setItemText(3, _translate("MainWindow", "Апр"))
        self.tmonthMenu.setItemText(4, _translate("MainWindow", "Май"))
        self.tmonthMenu.setItemText(5, _translate("MainWindow", "Июн"))
        self.tmonthMenu.setItemText(6, _translate("MainWindow", "Июл"))
        self.tmonthMenu.setItemText(7, _translate("MainWindow", "Авг"))
        self.tmonthMenu.setItemText(8, _translate("MainWindow", "Сен"))
        self.tmonthMenu.setItemText(9, _translate("MainWindow", "Окт"))
        self.tmonthMenu.setItemText(10, _translate("MainWindow", "Ноя"))
        self.tmonthMenu.setItemText(11, _translate("MainWindow", "Дек"))
        self.configbox.headerItem().setText(0, _translate("MainWindow", "Имя"))
        self.configbox.headerItem().setText(1, _translate("MainWindow", "Текст"))
        self.configbox.headerItem().setText(2, _translate("MainWindow", "Рубрика"))
        self.configbox.headerItem().setText(3, _translate("MainWindow", "Нач. дата"))
        self.configbox.headerItem().setText(4, _translate("MainWindow", "Кон. дата"))
        self.configbox.headerItem().setText(5, _translate("MainWindow", "Автор"))
        self.configbox.headerItem().setText(6, _translate("MainWindow", "Адресат"))
        self.configbox.headerItem().setText(7, _translate("MainWindow", "Расш. поиск"))
        __sortingEnabled = self.configbox.isSortingEnabled()
        self.configbox.setSortingEnabled(False)
        self.configbox.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "Конфигурации:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.manager), _translate("MainWindow", "Менеджер конфигураций"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Пользователь"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Сообщение"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Время"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Ссылка"))
        self.treeWidget.headerItem().setText(
            4, _translate("MainWindow", "Длина сообщения"))
        self.treeWidget.headerItem().setText(
            5, _translate("MainWindow", "Развернутый вид"))
        self.label_16.setText(_translate("MainWindow", "Выберите файл!"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пользователь"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Сообщение"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ссылка"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Длина сообщения"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Развернутый вид"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Значение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "Расширенный предпросмотр"))
        self.label_18.setText(_translate("MainWindow", "Настройки"))
        self.dateCheck.setText(_translate(
            "MainWindow", "Текущую дату и время"))
        self.cfgCheck.setText(_translate("MainWindow", "Текущую конфигурацию"))
        self.label_17.setText(_translate(
            "MainWindow", "Указывать в названии экспортированного файла"))
        self.label_19.setText(_translate("MainWindow", "Настройки приложения"))
        self.saveStgCheck.setText(_translate(
            "MainWindow", "Сохранять настройки при выходе"))
        self.loadStgCheck.setText(_translate(
            "MainWindow", "Загружать настройки при входе"))
        self.exitCheck.setText(_translate(
            "MainWindow", "Предупреждать о выходе из приложения"))
        self.exactTime.setText(_translate("MainWindow", "Конкретное время"))
        self.relativetime.setText(_translate(
            "MainWindow", "Относительное время"))
        self.label_20.setText(_translate(
            "MainWindow", "В списке всех конфигураций показывать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.settings), _translate("MainWindow", "Настройки"))
        self.tyearMenu.setCurrentIndex(20)
